name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  version: "0.0.${{ github.event.number }}.${{ github.run_number }}"
  outputFolder: "release"
  Timezone: America/Los_Angeles

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/neilenns/kicad:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Generate PDF
        run: |
          kicad-cli sch export pdf -D VERSION=${{ env.version }} -D DATE=${{ env.DATE }} --output ${{ env.outputFolder }}/dm13a-breakout-board.pdf dm13a-breakout-board.kicad_sch

      - name: Generate BOM
        run: |
          kicad-cli sch export bom --preset JLCPCB --output ${{ env.outputFolder }}/dm13a-breakout-board.csv dm13a-breakout-board.kicad_sch

      - name: Attach output
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: |
            "*.pdf"
            "*.csv"
