name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kicad/kicad:9.0 # Note: All commands will run using sh not bash
      options: --user root

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run kicad-cli ERC
      run: |
        kicad-cli sch erc dm13a-breakout-board.kicad_sch

    - name: Run kicad-cli DRC
      run: |
        kicad-cli pcb drc dm13a-breakout-board.kicad_pcb

    - name: Attach reports
      uses: actions/upload-artifact@v4
      with:
        name: report
        path: *.rpt