name: "Release"

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Design version"
        required: true
        default: "pre-release"

env:
  outputFolder: "release"
  projectName: "${{ github.event.repository.name }}"
  Timezone: "America/Los_Angeles"

jobs:
  FabricationAndDocumentation:
    runs-on: ubuntu-latest
    container: ghcr.io/neilenns/kicad:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Get the version of the GitHub release for use later. This is only valid
      # when run in a release context
      - name: Get GitHub release version
        id: get_github_version
        uses: battila7/get-version-action@v2
        if: startsWith(github.ref, 'refs/tags/')

      - name: Store GitHub release version
        id: save_github_version
        run: echo "version=${{ steps.get_github_version.outputs.version }}" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/')

      # Generate the various files
      - name: Generate PDF
        run: |
          kicad-cli sch export pdf -D VERSION=${{ env.version }} -D DATE=${{ env.DATE }} --output ${{ env.outputFolder }}/${{ env.projectName }}-schematic.pdf ${{ env.projectName }}.kicad_sch

      - name: Generate BOM
        run: |
          kicad-cli sch export bom --preset JLCPCB --output ${{ env.outputFolder }}/${{ env.projectName }}.csv ${{ env.projectName }}.kicad_sch

      # Install the zip command line tool to package up the output
      - name: Install zip
        uses: montudor/action-zip@v1

      # Bundle the output into the various zip files
      - name: Package output
        run: zip -qq -r ${{ env.projectName }}.zip ${{ env.outputFolder }}
        working-directory: ${{ env.OutputFolder }}

      # Upload all the zip files to the release.
      - name: Upload release files
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ env.OutputFolder }}/${{ env.projectName }}-schematic.pdf
            ${{ env.OutputFolder }}/${{ env.projectName }}.zip
