name: "Release"

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Design version"
        required: true
        default: "pre-release"

env:
  outputFolder: "release"
  projectName: "${{ github.event.repository.name }}"
  Timezone: "America/Los_Angeles"

jobs:
  FabricationAndDocumentation:
    runs-on: ubuntu-latest
    container: ghcr.io/neilenns/kicad:latest
    defaults:
        run:
          shell: bash
          
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Get the version of the GitHub release for use later. This is only valid
      # when run in a release context
      - name: Get GitHub release version
        id: get_github_version
        uses: dhkatz/get-version-action@v3.0.0
        if: startsWith(github.ref, 'refs/tags/')

      - name: Store GitHub release version
        id: save_github_version
        run: echo "version=${{ steps.get_github_version.outputs.version }}" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/')

      # Generate the various files
      - name: Generate PDF
        run: |
          kicad-cli sch export pdf -D VERSION=${{ env.version }} -D DATE=${{ env.DATE }} --output ${{ env.outputFolder }}/${{ env.projectName }}-schematic.pdf ${{ env.projectName }}.kicad_sch

      - name: Generate BOM
        run: |
          kicad-cli sch export bom \
          --preset JLCPCB \
          --output ${{ env.outputFolder }}/${{ env.projectName }}.csv \ 
          ${{ env.projectName }}.kicad_sch
    
      - name: Generate gerbers
        run: |
            kicad-cli pcb export gerbers \
            -D VERSION=${{ env.version }} \
            -D DATE=${{ env.DATE }} \
            --layers F.Cu,B.Cu,F.Paste,B.Paste,F.Silkscreen,B.Silkscreen,F.Mask,B.Mask,Edge.Cuts \
            --subtract-soldermask \
            --output ${{ env.outputFolder }}/gerbers \
            ${{ env.projectName }}.kicad_pcb

      - name: Generate drill files
        run: |
          kicad-cli pcb export drill \
          --generate-map \
          --output ${{ env.outputFolder }}/gerbers \
          ${{ env.projectName }}.kicad_pcb
          
      - name: Zip output
        run: zip -qq -r ${{ env.projectName }}.zip .
        working-directory: ${{ env.outputFolder }}

      # Upload all the zip files to the release.
      - name: Upload release files
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ env.outputFolder }}/${{ env.projectName }}-schematic.pdf
            ${{ env.outputFolder }}/${{ env.projectName }}.zip
